apiVersion: apps/v1
kind: Deployment
metadata:
  name: cass-operator
spec:
  selector:
    matchLabels:
      app: cass-operator
  template:
    metadata:
      labels:
        app: cass-operator
    spec:
      serviceAccountName: cass-operator
      containers:
       - image: pearlsprathap/cass-operator
         name: cass-operator
---
apiVersion: v1 
kind: ServiceAccount 
metadata: 
  name: cass-operator
---
apiVersion: rbac.authorization.k8s.io/v1 
kind: ClusterRoleBinding 
metadata: 
  name: cass-operator 
roleRef: 
  apiGroup: rbac.authorization.k8s.io 
  kind: ClusterRole 
  name: cluster-admin 
subjects: 
  - kind: ServiceAccount 
    name: cass-operator 
    namespace: default
